export const Icons = {
    boleto: require("./boleto.png"),
    bolsaVerde: require("./bolsa-verde.png"),
    bolsaPreto: require("./bolsa.png"),
    carteiraVerde: require("./carteira.png"),
    carteiraPreto: require("./carteira-icon.png"),
    cobrar: require("./cobrar.png"),
    iconCobrar: require("./cobrar-icon.png"),
    iconCobrarVerde: require("./cobrar-verde.png"),
    envie: require("./pix1.png"),
    homePreto: require("./home-preto.png"),
    homeVerde: require("./inicio.png"),
    iconQRCode: require("./qrcode.png"),
    iconQRCodeVerde: require("./qrcode-verde.png"),
    iconPix: require("./pix.png"),
    insira: require("./pix2.png"),
    notificacaoPreto: require("./notificacao.png"),
    notificacaoVerde: require("./notificacao-verde.png"),
    pagar: require("./pagar.png"),
    iconPagar: require("./codigo.png"),
    iconPagarVerde: require("./codigo-icon.png"),
    picpay: require("./picpay-icon.png"),
    pixVerde: require("./pix-verde.png"),
};

export const Images = {
    banner: require("./banner.png"),
    pixLogo: require("./pix-logo.png"),
    qrCode: require("./qrcode-imagem.png"),
};
